<?php

namespace Database\Seeders;

use App\Models\Grade;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class GradeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Grade::create(['min_grade' => 11, 'max_grade' => 12]);
        Grade::create(['min_grade' => 10, 'max_grade' => 10]);
        Grade::create(['min_grade' => 8, 'max_grade' => 8]);
        Grade::create(['min_grade' => 8, 'max_grade' => 8]);
        Grade::create(['min_grade' => 9, 'max_grade' => 9]);
        Grade::create(['min_grade' => 11, 'max_grade' => 12]);
        Grade::create(['min_grade' => 9, 'max_grade' => 10]);
        Grade::create(['min_grade' => 8, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 7]);
        Grade::create(['min_grade' => 9, 'max_grade' => 10]);
        Grade::create(['min_grade' => 7, 'max_grade' => 7]);
        Grade::create(['min_grade' => 8, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 8, 'max_grade' => 8]);
        Grade::create(['min_grade' => 9, 'max_grade' => 10]);
        Grade::create(['min_grade' => 11, 'max_grade' => 12]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 9, 'max_grade' => 10]);
        Grade::create(['min_grade' => 9, 'max_grade' => 10]);
        Grade::create(['min_grade' => 9, 'max_grade' => 9]);
        Grade::create(['min_grade' => 8, 'max_grade' => 8]);
        Grade::create(['min_grade' => 9, 'max_grade' => 10]);
        Grade::create(['min_grade' => 9, 'max_grade' => 10]);
        Grade::create(['min_grade' => 11, 'max_grade' => 12]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 9, 'max_grade' => 10]);
        Grade::create(['min_grade' => 9, 'max_grade' => 10]);
        Grade::create(['min_grade' => 9, 'max_grade' => 9]);
        Grade::create(['min_grade' => 8, 'max_grade' => 8]);
        Grade::create(['min_grade' => 8, 'max_grade' => 8]);
        Grade::create(['min_grade' => 9, 'max_grade' => 10]);
        Grade::create(['min_grade' => 9, 'max_grade' => 10]);
        Grade::create(['min_grade' => 11, 'max_grade' => 12]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 9, 'max_grade' => 10]);
        Grade::create(['min_grade' => 9, 'max_grade' => 10]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 11, 'max_grade' => 12]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 9, 'max_grade' => 10]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 9, 'max_grade' => 10]);
        Grade::create(['min_grade' => 11, 'max_grade' => 12]);
        Grade::create(['min_grade' => 9, 'max_grade' => 10]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 11, 'max_grade' => 12]);
        Grade::create(['min_grade' => 8, 'max_grade' => 9]);
        Grade::create(['min_grade' => 8, 'max_grade' => 9]);
        Grade::create(['min_grade' => 9, 'max_grade' => 10]);
        Grade::create(['min_grade' => 8, 'max_grade' => 9]);
        Grade::create(['min_grade' => 8, 'max_grade' => 9]);
        Grade::create(['min_grade' => 8, 'max_grade' => 9]);
        Grade::create(['min_grade' => 8, 'max_grade' => 9]);
        Grade::create(['min_grade' => 12, 'max_grade' => 99]);
        Grade::create(['min_grade' => 6, 'max_grade' => 7]);
        Grade::create(['min_grade' => 6, 'max_grade' => 7]);
        Grade::create(['min_grade' => 11, 'max_grade' => 12]);
        Grade::create(['min_grade' => 9, 'max_grade' => 10]);
        Grade::create(['min_grade' => 9, 'max_grade' => 10]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 0, 'max_grade' => 6]);
        Grade::create(['min_grade' => 6, 'max_grade' => 7]);
        Grade::create(['min_grade' => 6, 'max_grade' => 7]);
        Grade::create(['min_grade' => 0, 'max_grade' => 6]);
        Grade::create(['min_grade' => 8, 'max_grade' => 9]);
        Grade::create(['min_grade' => 8, 'max_grade' => 9]);
        Grade::create(['min_grade' => 8, 'max_grade' => 9]);
        Grade::create(['min_grade' => 8, 'max_grade' => 9]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 99]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 0, 'max_grade' => 7]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 99]);
        Grade::create(['min_grade' => 9, 'max_grade' => 10]);
        Grade::create(['min_grade' => 7, 'max_grade' => 99]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 11, 'max_grade' => 12]);
        Grade::create(['min_grade' => 11, 'max_grade' => 12]);
        Grade::create(['min_grade' => 9, 'max_grade' => 10]);
        Grade::create(['min_grade' => 9, 'max_grade' => 10]);
        Grade::create(['min_grade' => 9, 'max_grade' => 10]);
        Grade::create(['min_grade' => 9, 'max_grade' => 10]);
        Grade::create(['min_grade' => 7, 'max_grade' => 99]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 0, 'max_grade' => 7]);
        Grade::create(['min_grade' => 0, 'max_grade' => 7]);
        Grade::create(['min_grade' => 0, 'max_grade' => 7]);
        Grade::create(['min_grade' => 0, 'max_grade' => 7]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 7]);
        Grade::create(['min_grade' => 9, 'max_grade' => 9]);
        Grade::create(['min_grade' => 9, 'max_grade' => 9]);
        Grade::create(['min_grade' => 6, 'max_grade' => 7]);
        Grade::create(['min_grade' => 6, 'max_grade' => 7]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 11, 'max_grade' => 12]);
        Grade::create(['min_grade' => 9, 'max_grade' => 10]);
        Grade::create(['min_grade' => 9, 'max_grade' => 10]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 9, 'max_grade' => 10]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 11, 'max_grade' => 12]);
        Grade::create(['min_grade' => 0, 'max_grade' => 7]);
        Grade::create(['min_grade' => 0, 'max_grade' => 7]);
        Grade::create(['min_grade' => 11, 'max_grade' => 12]);
        Grade::create(['min_grade' => 9, 'max_grade' => 10]);
        Grade::create(['min_grade' => 9, 'max_grade' => 10]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 7, 'max_grade' => 8]);
        Grade::create(['min_grade' => 0, 'max_grade' => 7]);
        Grade::create(['min_grade' => 9, 'max_grade' => 10]);
    }
}
